// Browser preview only (vite dev without Tauri): the mods backend on sample data with simulated installs, so the game
// page can be designed and screenshotted. Items are real: Thunderstore (Lethal Company), Nexus Mods (Lethal Company,
// Balatro, Skyrim Special Edition), GameBanana (Lethal Company, Balatro) and Modrinth (Minecraft), titles, icons and
// counts as each source reported them on 2026-10-08. CurseForge and mod.io answer "source unavailable" (keys pending).
// Loaded by lib/mods.ts only outside the app.
// URL flags: ?nx=soon (Nexus login not open yet), ?nx=out (logged out), ?nx=premium.
import { ModsError, type InstallPlan, type InstalledModRow, type ModFile, type ModGame, type ModItem, type ModsBackend, type NexusStatus, type PlanFile } from './mods';

type Sample = ModItem & { deps?: string[]; file?: string; md5?: string };

const SAMPLE: Sample[] = [
  {"ref": "ts:BepInEx-BepInExPack", "title": "BepInExPack", "summary": "BepInEx pack for Mono Unity games. Preconfigured and ready to use.", "author": "BepInEx", "icon": "https://ccdn.thunderstore.io/live/repository/icons/BepInEx-BepInExPack-5.4.2305.png", "downloads": 33685986, "likes": 1018, "updated": 1773723921, "created": 1673972678, "version": "5.4.2305", "sizeBytes": 669238, "tags": ["BepInEx"], "url": "https://thunderstore.io/c/lethal-company/p/BepInEx/BepInExPack/", "source": "ts", "game": "lethal", "installable": true, "deps": []},
  {"ref": "ts:notnotnotswipez-MoreCompany", "title": "MoreCompany", "summary": "A stable lobby player count expansion mod. With cosmetics!", "author": "notnotnotswipez", "icon": "https://ccdn.thunderstore.io/live/repository/icons/notnotnotswipez-MoreCompany-1.14.0.png", "downloads": 26964768, "likes": 640, "updated": 1777080522, "created": 1700109987, "version": "1.14.0", "sizeBytes": 10530391, "tags": ["Mods", "BepInEx", "Tweaks & Quality Of Life"], "url": "https://thunderstore.io/c/lethal-company/p/notnotnotswipez/MoreCompany/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack"]},
  {"ref": "ts:Evaisa-LethalLib", "title": "LethalLib", "summary": "Personal modding tools for Lethal Company", "author": "Evaisa", "icon": "https://ccdn.thunderstore.io/live/repository/icons/Evaisa-LethalLib-1.2.0.png", "downloads": 24002849, "likes": 216, "updated": 1775073683, "created": 1700132323, "version": "1.2.0", "sizeBytes": 585539, "tags": ["Mods", "Tools", "Libraries", "BepInEx"], "url": "https://thunderstore.io/c/lethal-company/p/Evaisa/LethalLib/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack", "Evaisa-HookGenPatcher", "MonoDetour-MonoDetour_BepInEx_5"]},
  {"ref": "ts:FlipMods-ReservedItemSlotCore", "title": "ReservedItemSlotCore", "summary": "The core mod for all ReservedItemSlot mods. Adds functionality for all ReservedItemSlot mods and adds API functions! LCVR Compatible", "author": "FlipMods", "icon": "https://ccdn.thunderstore.io/live/repository/icons/FlipMods-ReservedItemSlotCore-2.0.55.png", "downloads": 22772962, "likes": 246, "updated": 1775944004, "created": 1700387724, "version": "2.0.55", "sizeBytes": 71834, "tags": ["Server-side", "Client-side", "BepInEx", "Mods", "Libraries"], "url": "https://thunderstore.io/c/lethal-company/p/FlipMods/ReservedItemSlotCore/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack"]},
  {"ref": "ts:Rune580-LethalCompany_InputUtils", "title": "LethalCompany InputUtils", "summary": "API/Library for creating Unity InputActions with in-game re-binding support. Provides an alternative UI that allows for supporting mods to have in-game re-bindable keybinds.", "author": "Rune580", "icon": "https://ccdn.thunderstore.io/live/repository/icons/Rune580-LethalCompany_InputUtils-0.7.13.png", "downloads": 19601541, "likes": 123, "updated": 1774975116, "created": 1702258202, "version": "0.7.13", "sizeBytes": 301879, "tags": ["Libraries"], "url": "https://thunderstore.io/c/lethal-company/p/Rune580/LethalCompany_InputUtils/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack"]},
  {"ref": "ts:FlipMods-TooManyEmotes", "title": "TooManyEmotes", "summary": "Adds over 300 new emotes! Includes emote wheel, allows Masked Enemies to emote, adds emote music (can be muted), implements a system for purchasing emotes on the store (optional), and much more!", "author": "FlipMods", "icon": "https://ccdn.thunderstore.io/live/repository/icons/FlipMods-TooManyEmotes-2.3.17.png", "downloads": 17879091, "likes": 313, "updated": 1780250277, "created": 1702444302, "version": "2.3.17", "sizeBytes": 124301815, "tags": ["Mods", "Client-side", "Emotes"], "url": "https://thunderstore.io/c/lethal-company/p/FlipMods/TooManyEmotes/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack", "Rune580-LethalCompany_InputUtils"]},
  {"ref": "ts:x753-More_Suits", "title": "More Suits", "summary": "Adds more suits to choose from, and can be used as a library to load your own suits!", "author": "x753", "icon": "https://ccdn.thunderstore.io/live/repository/icons/x753-More_Suits-1.5.4.png", "downloads": 17382856, "likes": 465, "updated": 1785376801, "created": 1700162077, "version": "1.5.4", "sizeBytes": 10055646, "tags": ["Mods", "Libraries", "Suits"], "url": "https://thunderstore.io/c/lethal-company/p/x753/More_Suits/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack"]},
  {"ref": "ts:FlipMods-ReservedFlashlightSlot", "title": "ReservedFlashlightSlot", "summary": "Gives a dedicated Flashlight slot on the right side of your screen that can optionally be purchased! Can be toggled with [F] to activate the Flashlight at anytime.", "author": "FlipMods", "icon": "https://ccdn.thunderstore.io/live/repository/icons/FlipMods-ReservedFlashlightSlot-2.0.10.png", "downloads": 16267392, "likes": 339, "updated": 1738632457, "created": 1700388167, "version": "2.0.10", "sizeBytes": 32222, "tags": ["Mods", "Equipment", "Client-side"], "url": "https://thunderstore.io/c/lethal-company/p/FlipMods/ReservedFlashlightSlot/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack", "FlipMods-ReservedItemSlotCore"]},
  {"ref": "ts:x753-Mimics", "title": "Mimics", "summary": "Adds a dangerous new monster to the game. Can you figure out what's real or will you be devoured?", "author": "x753", "icon": "https://ccdn.thunderstore.io/live/repository/icons/x753-Mimics-2.7.4.png", "downloads": 14284437, "likes": 377, "updated": 1775509108, "created": 1701647062, "version": "2.7.4", "sizeBytes": 7099613, "tags": ["Mods", "Monsters"], "url": "https://thunderstore.io/c/lethal-company/p/x753/Mimics/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack"]},
  {"ref": "ts:IAmBatby-LethalLevelLoader", "title": "LethalLevelLoader", "summary": "A Custom API to support the manual and dynamic integration of all forms of custom content in Lethal Company. (v81 Compatible)", "author": "IAmBatby", "icon": "https://ccdn.thunderstore.io/live/repository/icons/IAmBatby-LethalLevelLoader-1.7.13.png", "downloads": 13172325, "likes": 174, "updated": 1789728772, "created": 1704613618, "version": "1.7.13", "sizeBytes": 246066, "tags": ["Server-side", "Monsters", "Interiors", "Equipment", "Tools", "Moons", "BepInEx", "Mods", "Misc", "Libraries", "Posters", "Items"], "url": "https://thunderstore.io/c/lethal-company/p/IAmBatby/LethalLevelLoader/", "source": "ts", "game": "lethal", "installable": true, "deps": ["Evaisa-FixPluginTypesSerialization", "BepInEx-BepInExPack"]},
  {"ref": "ts:FlipMods-ReservedWalkieSlot", "title": "ReservedWalkieSlot", "summary": "Gives a dedicated Walkie slot on the right side of your screen that can optionally be purchased! You can press [X] to activate and speak into the Walkie at anytime.", "author": "FlipMods", "icon": "https://ccdn.thunderstore.io/live/repository/icons/FlipMods-ReservedWalkieSlot-2.0.7.png", "downloads": 12391138, "likes": 271, "updated": 1738550708, "created": 1700388063, "version": "2.0.7", "sizeBytes": 28932, "tags": ["Mods", "Equipment", "Client-side"], "url": "https://thunderstore.io/c/lethal-company/p/FlipMods/ReservedWalkieSlot/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack", "FlipMods-ReservedItemSlotCore"]},
  {"ref": "ts:malco-Lategame_Upgrades", "title": "Lategame Upgrades", "summary": "Mod focused on providing many upgrades which are purchaseable from the terminal through an interactive application. Most if not all of the available upgrades are configurable to allow customized experiences to everyone's liking.", "author": "malco", "icon": "https://ccdn.thunderstore.io/live/repository/icons/malco-Lategame_Upgrades-3.14.1.png", "downloads": 10669793, "likes": 300, "updated": 1786351521, "created": 1700981123, "version": "3.14.1", "sizeBytes": 25807684, "tags": ["Mods", "Equipment", "BepInEx", "Items"], "url": "https://thunderstore.io/c/lethal-company/p/malco/Lategame_Upgrades/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack", "Evaisa-LethalLib", "Evaisa-HookGenPatcher", "Sigurd-CSync", "Rune580-LethalCompany_InputUtils", "WhiteSpike-Interactive_Terminal_API"]},
  {"ref": "ts:Evaisa-HookGenPatcher", "title": "HookGenPatcher", "summary": "Generates MonoMod.RuntimeDetour.HookGen's MMHOOK file during the BepInEx preloader phase.", "author": "Evaisa", "icon": "https://ccdn.thunderstore.io/live/repository/icons/Evaisa-HookGenPatcher-0.0.5.png", "downloads": 9966082, "likes": 103, "updated": 1700589699, "created": 1700074885, "version": "0.0.5", "sizeBytes": 48862, "tags": ["Tools", "Misc", "Libraries", "BepInEx"], "url": "https://thunderstore.io/c/lethal-company/p/Evaisa/HookGenPatcher/", "source": "ts", "game": "lethal", "installable": true, "deps": []},
  {"ref": "ts:BunyaPineTree-ModelReplacementAPI", "title": "ModelReplacementAPI", "summary": "API to simplify model replacement", "author": "BunyaPineTree", "icon": "https://ccdn.thunderstore.io/live/repository/icons/BunyaPineTree-ModelReplacementAPI-2.4.20.png", "downloads": 9377892, "likes": 84, "updated": 1777841898, "created": 1701507612, "version": "2.4.20", "sizeBytes": 108093, "tags": ["Client-side", "Cosmetics", "BepInEx", "Libraries", "Asset Replacements"], "url": "https://thunderstore.io/c/lethal-company/p/BunyaPineTree/ModelReplacementAPI/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack"]},
  {"ref": "ts:loaforc-loaforcsSoundAPI", "title": "loaforcsSoundAPI", "summary": "A general use library to replace sounds in Unity games.", "author": "loaforc", "icon": "https://ccdn.thunderstore.io/live/repository/icons/loaforc-loaforcsSoundAPI-2.0.13.png", "downloads": 9205178, "likes": 71, "updated": 1787182862, "created": 1708168357, "version": "2.0.13", "sizeBytes": 89526, "tags": ["Audio", "Client-side", "Tools", "BepInEx", "Mods", "Libraries"], "url": "https://thunderstore.io/c/lethal-company/p/loaforc/loaforcsSoundAPI/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack"]},
  {"ref": "ts:sunnobunno-YippeeMod", "title": "YippeeMod", "summary": "Changes the chitter SFX of the Hoarding Bug to the yippee-tbh sound", "author": "sunnobunno", "icon": "https://ccdn.thunderstore.io/live/repository/icons/sunnobunno-YippeeMod-1.2.4.png", "downloads": 9071824, "likes": 334, "updated": 1708188545, "created": 1700605412, "version": "1.2.4", "sizeBytes": 110891, "tags": ["Mods", "Audio", "Client-side", "BepInEx"], "url": "https://thunderstore.io/c/lethal-company/p/sunnobunno/YippeeMod/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack"]},
  {"ref": "ts:Evaisa-LethalThings", "title": "LethalThings", "summary": "Adds 11 scrap, 6 store items, 1 enemy, 4 decor, 1 map hazard, and 1 game mechanic.", "author": "Evaisa", "icon": "https://ccdn.thunderstore.io/live/repository/icons/Evaisa-LethalThings-0.10.13.png", "downloads": 8559971, "likes": 271, "updated": 1761834375, "created": 1700166716, "version": "0.10.13", "sizeBytes": 32454474, "tags": ["Monsters", "BepInEx", "Mods", "Misc", "Equipment", "Items", "Furniture"], "url": "https://thunderstore.io/c/lethal-company/p/Evaisa/LethalThings/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack", "Evaisa-HookGenPatcher", "Evaisa-LethalLib"]},
  {"ref": "ts:AinaVT-LethalConfig", "title": "LethalConfig", "summary": "Provides an in-game config menu for players to edit their configs, and an API for other mods to use and customize their entries.", "author": "AinaVT", "icon": "https://ccdn.thunderstore.io/live/repository/icons/AinaVT-LethalConfig-1.4.6.png", "downloads": 8549730, "likes": 118, "updated": 1738800026, "created": 1704155361, "version": "1.4.6", "sizeBytes": 413013, "tags": ["Client-side", "Tools", "BepInEx", "Mods", "Libraries"], "url": "https://thunderstore.io/c/lethal-company/p/AinaVT/LethalConfig/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack"]},
  {"ref": "ts:Gemumoddo-LethalEmotesAPI", "title": "LethalEmotesAPI", "summary": "API for adding emotes to Lethal Company", "author": "Gemumoddo", "icon": "https://ccdn.thunderstore.io/live/repository/icons/Gemumoddo-LethalEmotesAPI-1.18.0.png", "downloads": 7622109, "likes": 38, "updated": 1775532519, "created": 1703121384, "version": "1.18.0", "sizeBytes": 35619302, "tags": ["Mods", "Libraries", "Emotes"], "url": "https://thunderstore.io/c/lethal-company/p/Gemumoddo/LethalEmotesAPI/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack", "Rune580-LethalCompany_InputUtils"]},
  {"ref": "ts:Verity-TooManySuits", "title": "TooManySuits", "summary": "More Suits Addon that adds pages to the suit rack.", "author": "Verity", "icon": "https://ccdn.thunderstore.io/live/repository/icons/Verity-TooManySuits-2.0.4.png", "downloads": 7565906, "likes": 181, "updated": 1780788738, "created": 1701767930, "version": "2.0.4", "sizeBytes": 186248, "tags": ["Mods", "Cosmetics", "BepInEx", "Suits"], "url": "https://thunderstore.io/c/lethal-company/p/Verity/TooManySuits/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack", "x753-More_Suits"]},
  {"ref": "ts:Hamunii-DetourContext_Dispose_Fix", "title": "DetourContext Dispose Fix", "summary": "A BepInEx patcher to fix MonoMod.RuntimeDetour's DetourContext.Dispose not working.", "author": "Hamunii", "icon": "https://ccdn.thunderstore.io/live/repository/icons/Hamunii-DetourContext_Dispose_Fix-1.0.9.png", "downloads": 7405528, "likes": 29, "updated": 1777746461, "created": 1711910656, "version": "1.0.9", "sizeBytes": 29571, "tags": ["BepInEx"], "url": "https://thunderstore.io/c/lethal-company/p/Hamunii/DetourContext_Dispose_Fix/", "source": "ts", "game": "lethal", "installable": true, "deps": ["BepInEx-BepInExPack"]},
  {"ref": "nx:lethalcompany:42", "source": "nx", "game": "lethal", "title": "BepInEx", "summary": "BepInEx pack for Mono Unity games. Preconfigured and ready to use.", "author": "BepInEx", "icon": "https://staticdelivery.nexusmods.com/mods/5848/images/thumbnails/42/42-1701822937-125506829.png", "downloads": 228127, "likes": 2532, "updated": 1701822958, "created": 1701822958, "version": "5.4.2200", "sizeBytes": 622592, "tags": ["Miscellaneous"], "url": "https://www.nexusmods.com/lethalcompany/mods/42", "installable": true},
  {"ref": "nx:lethalcompany:60", "source": "nx", "game": "lethal", "title": "More Company", "summary": "This mod is a lobby player count expansion mod. It increases the max player count.The mod is specifically designed for 8 players. Not every UI modification will properly accomodate for above 8 players.", "author": "Cyb3rdev", "icon": "https://staticdelivery.nexusmods.com/mods/5848/images/thumbnails/60/60-1702164172-1901700031.jpeg", "downloads": 175251, "likes": 1820, "updated": 1787872724, "created": 1702164506, "version": "1.14.0", "sizeBytes": 10470400, "tags": ["Gameplay"], "url": "https://www.nexusmods.com/lethalcompany/mods/60", "installable": true},
  {"ref": "nx:lethalcompany:11", "source": "nx", "game": "lethal", "title": "ShipLoot", "summary": "Reliably displays the total scrap value on the ship.", "author": "Raqzas", "icon": "https://staticdelivery.nexusmods.com/mods/5848/images/thumbnails/11/11-1700518935-308068677.png", "downloads": 76678, "likes": 990, "updated": 1711203914, "created": 1700519038, "version": "v1.1", "sizeBytes": 57344, "tags": ["Gameplay"], "url": "https://www.nexusmods.com/lethalcompany/mods/11", "installable": true},
  {"ref": "nx:lethalcompany:8", "source": "nx", "game": "lethal", "title": "Fix Resolution", "summary": "Changes the render resolution to your screens resolution rather than 520p.", "author": "kruumy", "icon": "https://staticdelivery.nexusmods.com/mods/5848/images/thumbnails/8/8-1700454509-1842037962.png", "downloads": 62834, "likes": 839, "updated": 1700454801, "created": 1700454801, "version": "1.0.0", "sizeBytes": 3072, "tags": ["Miscellaneous"], "url": "https://www.nexusmods.com/lethalcompany/mods/8", "installable": true},
  {"ref": "nx:lethalcompany:110", "source": "nx", "game": "lethal", "title": "PDK's Cheat Mod Menu", "summary": "Lethal Company cheat mod menu with 30+ features. God mode. Infinite sprint. Set leaderboard rank. Force start game. Send a message as someone else...", "author": "PDK", "icon": "https://staticdelivery.nexusmods.com/mods/5848/images/thumbnails/110/110-1703552416-420732696.png", "downloads": 70919, "likes": 720, "updated": 1788198742, "created": 1703553151, "version": "3.0.6", "sizeBytes": 75776, "tags": ["Miscellaneous"], "url": "https://www.nexusmods.com/lethalcompany/mods/110", "installable": true},
  {"ref": "nx:lethalcompany:18", "source": "nx", "game": "lethal", "title": "Minimap", "summary": "The first fully customizable client-sided Minimap mod for Lethal Company. All configurations and hotkeys can be managed via a user-friendly in-game GUI. Suitable for both solo and co-op players!", "author": "Tyzeron", "icon": "https://staticdelivery.nexusmods.com/mods/5848/images/thumbnails/18/18-1700726976-1088246521.png", "downloads": 43760, "likes": 659, "updated": 1749171617, "created": 1700686836, "version": "1.0.6", "sizeBytes": 67584, "tags": ["Gameplay"], "url": "https://www.nexusmods.com/lethalcompany/mods/18", "installable": true},
  {"ref": "nx:lethalcompany:21", "source": "nx", "game": "lethal", "title": "Helmet Cameras", "summary": "Mod adds pov helmet cameras for players, that displays video on the second large monitor at ship. For better CameraMan/ShipGuy/Operator experience for my opinion.", "author": "RickArg", "icon": "https://staticdelivery.nexusmods.com/mods/5848/images/thumbnails/21/21-1700852683-126319928.png", "downloads": 56445, "likes": 643, "updated": 1702284394, "created": 1700853318, "version": "2.1.5", "sizeBytes": 7168, "tags": ["Gameplay"], "url": "https://www.nexusmods.com/lethalcompany/mods/21", "installable": true},
  {"ref": "nx:lethalcompany:29", "source": "nx", "game": "lethal", "title": "Extra Inventory Slots for bep 5 and 6", "summary": "Increases your inventory size to 8 slots! BOTH BEPINEX VERSIONS SUPPORTED! WOOHOO!IF YOU GRAB THE DLL BUT NOT THE WHOLE BEPINEX INSTALL I'VE LEFT, THEN YOU NEED TO SET HideGameManagerObject to true in Lethal", "author": "Daltonyx", "icon": "https://staticdelivery.nexusmods.com/mods/5848/images/thumbnails/29/29-1701253300-202152635.png", "downloads": 27685, "likes": 417, "updated": 1701838470, "created": 1701253359, "version": "1.1", "sizeBytes": 4052992, "tags": ["Gameplay"], "url": "https://www.nexusmods.com/lethalcompany/mods/29", "installable": true},
  {"ref": "nx:lethalcompany:70", "source": "nx", "game": "lethal", "title": "HDLethalCompany", "summary": "Additional graphics settings such as resolution, anti-aliasing, fog quality etc.", "author": "Cyb3rdev", "icon": "https://staticdelivery.nexusmods.com/mods/5848/images/thumbnails/70/70-1702252087-1026092489.jpeg", "downloads": 23286, "likes": 335, "updated": 1720666829, "created": 1702252287, "version": "1.5.6", "sizeBytes": 102400, "tags": ["Gameplay"], "url": "https://www.nexusmods.com/lethalcompany/mods/70", "installable": true},
  {"ref": "nx:lethalcompany:23", "source": "nx", "game": "lethal", "title": "Boombox Controller", "summary": "This mod allows you to easily upload a track to the boombox by using chatIf you liked the mod, please don't forget to give it a thumbs up", "author": "KoderTeh", "icon": "https://staticdelivery.nexusmods.com/mods/5848/images/thumbnails/23/23-1703272314-551499776.png", "downloads": 25392, "likes": 309, "updated": 1739384113, "created": 1701025636, "version": "1.2.7", "sizeBytes": 106496, "tags": ["Miscellaneous"], "url": "https://www.nexusmods.com/lethalcompany/mods/23", "installable": true},
  {"ref": "nx:balatro:45", "source": "nx", "game": "balatro", "title": "Steamodded (Smods)", "summary": "A Balatro Modding Framework", "author": "Steamopollys", "icon": "https://staticdelivery.nexusmods.com/mods/6217/images/thumbnails/45/45-1742701023-1857153383.png", "downloads": 103865, "likes": 967, "updated": 1770036827, "created": 1720051829, "version": "1.0.0-beta-1224a", "sizeBytes": 595968, "tags": ["Miscellaneous"], "url": "https://www.nexusmods.com/balatro/mods/45", "installable": true},
  {"ref": "nx:balatro:58", "source": "nx", "game": "balatro", "title": "Pokermon", "summary": "Huge thank you to Lovely, Steamodded and Cryptid for making this possible. Pokermon is a full content mod for Balatro, adding content based on Pokemon. There are 200(!!) new Jokers and many other custom additions. There is also an option to", "author": "InertSteak", "icon": "https://staticdelivery.nexusmods.com/mods/6217/images/thumbnails/58/58-1729097358-1918593832.png", "downloads": 82348, "likes": 839, "updated": 1789261321, "created": 1728349101, "version": "3.9.0", "sizeBytes": 51737600, "tags": ["Cards"], "url": "https://www.nexusmods.com/balatro/mods/58", "installable": true},
  {"ref": "nx:balatro:41", "source": "nx", "game": "balatro", "title": "Balustro", "summary": "Changes a bunch of things to lewd assets, custom drawn for Balatro, as well as several optional text changes.", "author": "Various Artists and someone23832", "icon": "https://staticdelivery.nexusmods.com/mods/6217/images/thumbnails/41/41-1754385888-572876580.jpg", "downloads": 39429, "likes": 799, "updated": 1754387766, "created": 1718478790, "version": "0.14", "sizeBytes": 5159936, "tags": ["Miscellaneous"], "url": "https://www.nexusmods.com/balatro/mods/41", "installable": true, "nsfw": true},
  {"ref": "nx:balatro:1", "source": "nx", "game": "balatro", "title": "Balatro - Hidden Aces Edition (DISCONTINUED BUT FUNCTIONAL)", "summary": "Destroy the competition and rob them blind.", "author": "JewTron", "icon": "https://staticdelivery.nexusmods.com/mods/6217/images/thumbnails/1/1-1709626612-1899674685.jpeg", "downloads": 33342, "likes": 489, "updated": 1736993260, "created": 1709831061, "version": "1.0", "sizeBytes": 55538688, "tags": ["Gameplay"], "url": "https://www.nexusmods.com/balatro/mods/1", "installable": true},
  {"ref": "nx:balatro:177", "source": "nx", "game": "balatro", "title": "Yuri Blueprint Brainstorm", "summary": "anime yuri couple", "author": "eaze", "icon": "https://staticdelivery.nexusmods.com/mods/6217/images/thumbnails/177/177-1737720972-1773313933.png", "downloads": 14732, "likes": 345, "updated": 1737721623, "created": 1737721623, "version": "1.0", "sizeBytes": 24576, "tags": ["Miscellaneous"], "url": "https://www.nexusmods.com/balatro/mods/177", "installable": true},
  {"ref": "nx:balatro:12", "source": "nx", "game": "balatro", "title": "Mika's Mod Collection", "summary": "A content mod adding 60 Jokers and more!", "author": "Mikadoe", "icon": "https://staticdelivery.nexusmods.com/mods/6217/images/thumbnails/12/12-1714164903-1043689415.png", "downloads": 25331, "likes": 315, "updated": 1715028537, "created": 1711891354, "version": "V0.13.1", "sizeBytes": 399360, "tags": ["Miscellaneous"], "url": "https://www.nexusmods.com/balatro/mods/12", "installable": true},
  {"ref": "nx:balatro:11", "source": "nx", "game": "balatro", "title": "Choose First Shop Joker - (Discontinued FUNCTIONAL)", "summary": "This mod adds a way to choose the first joker that spawns", "author": "infarctus", "icon": "https://staticdelivery.nexusmods.com/mods/6217/images/thumbnails/11/11-1711323004-1920500804.jpeg", "downloads": 26232, "likes": 307, "updated": 1711738020, "created": 1711323244, "version": "1.0.0", "sizeBytes": 1024, "tags": ["Gameplay"], "url": "https://www.nexusmods.com/balatro/mods/11", "installable": true},
  {"ref": "nx:balatro:96", "source": "nx", "game": "balatro", "title": "Balatro Plus", "summary": "This Mods add many new contents to Balatro.", "author": "SomeCoder99", "icon": "https://staticdelivery.nexusmods.com/mods/6217/images/thumbnails/96/96-1736036358-1691455245.png", "downloads": 27526, "likes": 288, "updated": 1746439846, "created": 1735722751, "version": "1.0.2", "sizeBytes": 612352, "tags": ["Miscellaneous"], "url": "https://www.nexusmods.com/balatro/mods/96", "installable": true},
  {"ref": "nx:balatro:114", "source": "nx", "game": "balatro", "title": "Bocchi The Rock Deck Skin", "summary": "Bocchi the Rock Deck Skin!", "author": "Turpix", "icon": "https://staticdelivery.nexusmods.com/mods/6217/images/thumbnails/114/114-1736092599-634508409.jpeg", "downloads": 13687, "likes": 273, "updated": 1736123912, "created": 1736079359, "version": "2.1", "sizeBytes": 543744, "tags": ["Cards"], "url": "https://www.nexusmods.com/balatro/mods/114", "installable": true},
  {"ref": "nx:balatro:69", "source": "nx", "game": "balatro", "title": "Preorder Cards", "summary": "Preordering the cards you want in the collection menu.", "author": "asd123cqp", "icon": "https://staticdelivery.nexusmods.com/mods/6217/images/thumbnails/69/69-1732673792-1054222634.png", "downloads": 19732, "likes": 259, "updated": 1735086456, "created": 1732674114, "version": "0.5.1", "sizeBytes": 2048, "tags": ["Gameplay"], "url": "https://www.nexusmods.com/balatro/mods/69", "installable": true},
  {"ref": "nx:skyrimspecialedition:12604", "source": "nx", "game": "skyrim", "title": "SkyUI", "summary": "Elegant, PC-friendly interface mod with many advanced features. Upgraded with full support for all modern game versions.", "author": "SkyUI Team", "icon": "https://staticdelivery.nexusmods.com/mods/1704/images/thumbnails/12604/12604-1774356382-945468655.png", "downloads": 26014624, "likes": 504670, "updated": 1778020881, "created": 1506858943, "version": "6.9", "sizeBytes": 2693120, "tags": ["User Interface"], "url": "https://www.nexusmods.com/skyrimspecialedition/mods/12604", "installable": true},
  {"ref": "nx:skyrimspecialedition:266", "source": "nx", "game": "skyrim", "title": "Unofficial Skyrim Special Edition Patch - USSEP", "summary": "A comprehensive bugfixing mod for The Elder Scrolls V: Skyrim - Special Edition. The goal of the Unofficial Skyrim Special Edition Patch (aka USSEP) is to eventually fix every bug with Skyrim Special Edition not officially resolved by the", "author": "The Unofficial Patch Project Team", "icon": "https://staticdelivery.nexusmods.com/mods/1704/images/thumbnails/266-0-1477512662.png", "downloads": 28022774, "likes": 478932, "updated": 1788646929, "created": 1477512842, "version": "4.3.9c", "sizeBytes": 168852480, "tags": ["Bug Fixes"], "url": "https://www.nexusmods.com/skyrimspecialedition/mods/266", "installable": true},
  {"ref": "nx:skyrimspecialedition:6194", "source": "nx", "game": "skyrim", "title": "Mod Organizer 2", "summary": "Mod Organizer (MO) is a tool for managing mod collections of arbitrary size. It is specifically designed for people who like to experiment with mods and thus need an easy and reliable way to install and uninstall them.", "author": "Tannin - MO2 Team", "icon": "https://staticdelivery.nexusmods.com/mods/1704/images/thumbnails/6194/6194-1525726634-1392239594.png", "downloads": 11007443, "likes": 467385, "updated": 1776678197, "created": 1481783109, "version": "2.5.2", "sizeBytes": 147501056, "tags": ["Utilities"], "url": "https://www.nexusmods.com/skyrimspecialedition/mods/6194", "installable": true},
  {"ref": "nx:skyrimspecialedition:32444", "source": "nx", "game": "skyrim", "title": "Address Library for SKSE Plugins", "summary": "Database to make SKSE DLL plugins version independent easily.", "author": "meh321", "icon": "https://staticdelivery.nexusmods.com/mods/1704/images/thumbnails/32444/32444-1581072939-1625378722.png", "downloads": 26230180, "likes": 282186, "updated": 1787844629, "created": 1581073336, "version": "13", "sizeBytes": 5303296, "tags": ["Modders Resources"], "url": "https://www.nexusmods.com/skyrimspecialedition/mods/32444", "installable": true},
  {"ref": "nx:skyrimspecialedition:659", "source": "nx", "game": "skyrim", "title": "Static Mesh Improvement Mod - SMIM", "summary": "A massive project to greatly improve the appearance of countless static 3D models in Skyrim. Basically, this is my attempt to make the Skyrim architecture, clutter, furniture, and landscaping much nicer.", "author": "Brumbek", "icon": "https://staticdelivery.nexusmods.com/mods/1704/images/thumbnails/8655-1-1344844621.jpg", "downloads": 17260305, "likes": 273185, "updated": 1739741945, "created": 1477711304, "version": "2.08", "sizeBytes": 1057146880, "tags": ["Models and Textures"], "url": "https://www.nexusmods.com/skyrimspecialedition/mods/659", "installable": true},
  {"ref": "nx:skyrimspecialedition:19080", "source": "nx", "game": "skyrim", "title": "RaceMenu", "summary": "Complete overhaul to the character creation menu including new customization features such as multiple RGBA warpaints, body paints, hand paint, and foot paints. (Requires SKSE)", "author": "Expired", "icon": "https://staticdelivery.nexusmods.com/mods/1704/images/thumbnails/19080/19080-1776621005-385672924.jpg", "downloads": 22774907, "likes": 269418, "updated": 1776703223, "created": 1533487666, "version": "0.4.20", "sizeBytes": 8657920, "tags": ["User Interface"], "url": "https://www.nexusmods.com/skyrimspecialedition/mods/19080", "installable": true},
  {"ref": "nx:skyrimspecialedition:3038", "source": "nx", "game": "skyrim", "title": "Fores New Idles in Skyrim SE - FNIS SE", "summary": "No custom animation possible for Skyrim? Wrong. FNIS Behaviors allows to add different types of animations to the game: idles/poses, sequenced, furniture, paired, killmoves, creatures, and others.", "author": "fore", "icon": "https://staticdelivery.nexusmods.com/mods/1704/images/thumbnails/11811-1-1364819540.jpg", "downloads": 19205895, "likes": 261606, "updated": 1582110624, "created": 1478390879, "version": "7.6", "sizeBytes": 3748864, "tags": ["Animation"], "url": "https://www.nexusmods.com/skyrimspecialedition/mods/3038", "installable": true},
  {"ref": "nx:skyrimspecialedition:5804", "source": "nx", "game": "skyrim", "title": "A Quality World Map", "summary": "Provides a new set of highly-detailed 3D or paper world map textures, complete with roads! Also adds a detailed Solsteim map.", "author": "IcePenguin", "icon": "https://staticdelivery.nexusmods.com/mods/1704/images/thumbnails/5804-1-1481088259.jpg", "downloads": 11820874, "likes": 252546, "updated": 1481474913, "created": 1481089528, "version": "9.0.1", "sizeBytes": 21683200, "tags": ["User Interface"], "url": "https://www.nexusmods.com/skyrimspecialedition/mods/5804", "installable": true},
  {"ref": "nx:skyrimspecialedition:198", "source": "nx", "game": "skyrim", "title": "Caliente's Beautiful Bodies Enhancer -CBBE-", "summary": "The well-known body enhancer made famous in Skyrim is back and enhanced for Skyrim Special Edition.", "author": "Ousnius - Caliente - Jeir", "icon": "https://staticdelivery.nexusmods.com/mods/1704/images/thumbnails/198-8-1506556902.jpg", "downloads": 19088064, "likes": 248824, "updated": 1736604371, "created": 1506812519, "version": "2.0.3", "sizeBytes": 190913536, "tags": ["Body, Face, and Hair"], "url": "https://www.nexusmods.com/skyrimspecialedition/mods/198", "installable": true, "nsfw": true},
  {"ref": "nx:skyrimspecialedition:1988", "source": "nx", "game": "skyrim", "title": "XP32 Maximum Skeleton Special Extended - XPMSSE", "summary": "XP32 Maximum Skeleton Special Extended is the update of XP32 Maximum Skeleton Extended for Skyrim Special Edition.", "author": "Team XPMSE", "icon": "https://staticdelivery.nexusmods.com/mods/1704/images/thumbnails/1988/1988-1692502500-1543505880.jpeg", "downloads": 18133520, "likes": 246643, "updated": 1707663131, "created": 1477965676, "version": "5.06", "sizeBytes": 2365440, "tags": ["Animation"], "url": "https://www.nexusmods.com/skyrimspecialedition/mods/1988", "installable": true, "nsfw": true},
  {"ref": "gb:Mod:478468", "source": "gb", "game": "lethal", "title": "Clearer Cameras", "summary": "Upgrades the ship cameras to a clean 1024x1024 resolution so you can actually see out of them! The original resolution was 40x45, and I couldn't use them at all. So I made this mod. Warning: this mod adds two 1024x1024 displays, if you have", "author": "Zetalasis", "icon": "https://images.gamebanana.com/img/ss/mods/530-90_654eb36070051.jpg", "downloads": 976, "likes": 3, "updated": 1699656680, "created": 1699656680, "sizeBytes": 3244, "tags": ["Other/Misc"], "url": "https://gamebanana.com/mods/478468", "installable": true, "file": "clearercameras.zip", "md5": "7c9d1abffb8f7a0ba51156de3b9feca2"},
  {"ref": "gb:Mod:478835", "source": "gb", "game": "lethal", "title": "Bigger Hotbar", "summary": "This mod simply increases your hotbar size to 5, from the default (4).", "author": "flipf17", "icon": "https://images.gamebanana.com/img/ss/mods/530-90_6551659465015.jpg", "downloads": 926, "likes": 7, "updated": 1699833242, "created": 1699818136, "version": "1.0.0", "sizeBytes": 2975, "tags": ["Other/Misc"], "url": "https://gamebanana.com/mods/478835", "installable": true, "file": "biggerhotbar.7z", "md5": "26f5494eaa30f57e199975d8d750d439"},
  {"ref": "gb:Mod:478847", "source": "gb", "game": "lethal", "title": "Better Sprinting", "summary": "You do not have to download this mod if you don't want to. (obviously) But please don't criticize this mod, or those who might want to use this mod, for being \"cheaty\", as I tried to balance it enough where it felt natural. This mod does ma", "author": "flipf17", "icon": "https://images.gamebanana.com/img/ss/mods/655136e245328.jpg", "downloads": 778, "likes": 1, "updated": 1699821479, "created": 1699821479, "version": "1.0.2", "sizeBytes": 2817, "tags": ["Other/Misc"], "url": "https://gamebanana.com/mods/478847", "installable": true, "file": "bettersprinting.7z", "md5": "300332c5ee9d9d1b4509504157825658"},
  {"ref": "gb:Mod:479090", "source": "gb", "game": "lethal", "title": "Extra Players", "summary": "Allows up to ten players to play on Lethal Company. Probably will have some bugs as I could've missed another hardcoded value Game Updates will likely break this mod as I'm patching the raw assembly using CIL. Requires BepInEx to function. ", "author": "Creativious", "icon": "https://images.gamebanana.com/img/ss/mods/530-90_655335774610a.jpg", "downloads": 574, "likes": 4, "updated": 1701127847, "created": 1699952069, "version": "v0.1.0", "sizeBytes": 4609, "tags": ["Other/Misc"], "url": "https://gamebanana.com/mods/479090", "installable": true, "file": "extraplayers_d7eb0.7z", "md5": "e94f116b6aeecafa3b06fe327e8e67a7"},
  {"ref": "gb:Mod:493010", "source": "gb", "game": "lethal", "title": "LethalShading (ReShade Preset)", "summary": "LETHAL COMPANY WITH RTX! Or so thats what this ReShade preset will make you think... This is a simple ReShade preset that makes Lethal Company look very nice with some bloom, blur, and more shader things! This preset will make Lethal Compan", "author": "FlankoTanko!", "icon": "https://images.gamebanana.com/img/ss/mods/530-90_65b962b226537.jpg", "downloads": 364, "likes": 2, "updated": 1706824073, "created": 1706648395, "version": "1.10", "sizeBytes": 8474, "tags": ["Other/Misc"], "url": "https://gamebanana.com/mods/493010", "installable": true, "file": "lethalshading_69515.zip", "md5": "d4bd42e21e89f2a7c84c7b589bd419cc"},
  {"ref": "gb:Mod:478850", "source": "gb", "game": "lethal", "title": "Better Hotbar Swapping", "summary": "This mod simply increases the speed at which you can switch between your hotbar slots, because I felt like it was too slow for what I like. This mod is also supposed to let you activate your items faster, such as your flashlight, but it see", "author": "flipf17", "icon": "https://images.gamebanana.com/img/ss/mods/65513a2fb3303.jpg", "downloads": 252, "likes": 1, "updated": 1699833302, "created": 1699822217, "version": "1.0.0", "sizeBytes": 2523, "tags": ["Other/Misc"], "url": "https://gamebanana.com/mods/478850", "installable": true, "file": "betterhotbarswapping.7z", "md5": "16333b54adcc0eaf6d07c9cf98403e3e"},
  {"ref": "gb:Mod:483339", "source": "gb", "game": "lethal", "title": "Bigger Lobby [ GameBanana version ]", "summary": "THESE MODS WERE NOT CREATED BY ME, I AM JUST GIVING YOU A READY VERSION OF THE MODS \"BepInEx\" Made by ManlyMarco \"LC API\" Made by 2018 \"BiggerLobby\" made by bizzlemip However, this mod collection was made to make mod application easier, and", "author": "JJMAGame", "icon": "https://images.gamebanana.com/img/ss/mods/530-90_6574eaa8ddc20.jpg", "downloads": 241, "likes": 1, "updated": 1702784772, "created": 1702161201, "version": "V45", "sizeBytes": 640926, "tags": ["Other/Misc"], "url": "https://gamebanana.com/mods/483339", "installable": true, "file": "bigger_lobby_gamebanana_version_2.rar", "md5": "f7694d31160e69dc71801f6ce64b7101"},
  {"ref": "gb:Mod:478840", "source": "gb", "game": "lethal", "title": "Faster Item Dropship", "summary": "This mod will make the item dropship arrive in about 10 seconds. If you bought items before your player ship lands, the item dropship will land on the moon around the same time as you, or shortly after. The dropship will also leave sooner. ", "author": "flipf17", "icon": "https://images.gamebanana.com/img/ss/mods/530-90_65512dcb18a57.jpg", "downloads": 222, "likes": 0, "updated": 1699819137, "created": 1699819137, "version": "1.0.1", "sizeBytes": 2845, "tags": ["Other/Misc"], "url": "https://gamebanana.com/mods/478840", "installable": true, "file": "fasteritemdropship.7z", "md5": "a14ecc75941719f3c9654b531ce8d118"},
  {"ref": "gb:Mod:601535", "source": "gb", "game": "balatro", "title": "Deltarune Deck", "summary": "Replaces default face cards king, queen, jack, to Deltarune characters.", "author": "nolo33lp", "icon": "https://images.gamebanana.com/img/ss/mods/530-90_685421d98edcf.jpg", "downloads": 10527, "likes": 77, "updated": 1750377193, "created": 1750344225, "sizeBytes": 265138, "tags": ["Skins"], "url": "https://gamebanana.com/mods/601535", "installable": true, "file": "deltarunedeck_ee567.rar", "md5": "00d07bd09343fa38eb69f46df858a966"},
  {"ref": "gb:Mod:581178", "source": "gb", "game": "balatro", "title": "Vocaloid deck", "summary": "skin changes for J, Q, K of vocaloids / Utau /HL2 characters", "author": "nolo33lp", "icon": "https://images.gamebanana.com/img/ss/mods/530-90_67d26632d09f3.jpg", "downloads": 7853, "likes": 70, "updated": 1741997580, "created": 1741842171, "version": "1.1", "sizeBytes": 315334, "tags": ["Skins"], "url": "https://gamebanana.com/mods/581178", "installable": true, "file": "vocaloiddeck_d30df.rar", "md5": "8de50e33ea8db7499a9e432af086adaf"},
  {"ref": "gb:Mod:589198", "source": "gb", "game": "balatro", "title": "Hollow knight Deck", "summary": "skin changes for J, Q, K of Hollow knight", "author": "nolo33lp", "icon": "https://images.gamebanana.com/img/ss/mods/530-90_680331525eb1e.jpg", "downloads": 4922, "likes": 18, "updated": 1745039741, "created": 1745039741, "sizeBytes": 318707, "tags": ["Skins"], "url": "https://gamebanana.com/mods/589198", "installable": true, "file": "hollowknightdeck.rar", "md5": "6766afa32deaf9f799975cb32926cf19"},
  {"ref": "gb:Mod:591945", "source": "gb", "game": "balatro", "title": "Undertale Deck", "summary": "Replaces default face cards king, queen, jack, to Undertale characters", "author": "nolo33lp", "icon": "https://images.gamebanana.com/img/ss/mods/530-90_681516e7a7ced.jpg", "downloads": 4532, "likes": 19, "updated": 1746222287, "created": 1746212613, "sizeBytes": 278480, "tags": ["Skins"], "url": "https://gamebanana.com/mods/591945", "installable": true, "file": "undertaledeck.rar", "md5": "19392818cb471f880c6eaee8427e0805"},
  {"ref": "gb:Mod:590207", "source": "gb", "game": "balatro", "title": "Balatro Repainted", "summary": "Your favorite card game got a new coat of paint. Features: -Edits to all textures (Jokers, Blinds, Vouchers, Cards, etc.) -Edits to SFX -Edits to Text (English only) Full credits are included with the download Enjoy", "author": "howquaint", "icon": "https://images.gamebanana.com/img/ss/mods/530-90_68098a9b8882c.jpg", "downloads": 2625, "likes": 13, "updated": 1747948974, "created": 1745456991, "version": "1.1 I guess", "sizeBytes": 13811650, "tags": ["Skins"], "url": "https://gamebanana.com/mods/590207", "installable": true, "file": "balatro_repainted_e4022.zip", "md5": "cade76050e1ea77eefdd962595581c17"},
  {"ref": "gb:Mod:587443", "source": "gb", "game": "balatro", "title": "ENA: Dream BBQ Deck", "summary": "A mod for Balatro that replaces default face cards king, queen, jack, to Coral Glasses, Taski Maiden, Froggy, and ENA from ENA: Dream BBQ.", "author": "KeeganKeegan", "icon": "https://images.gamebanana.com/img/ss/mods/530-90_67f70bc3af3a4.jpg", "downloads": 1289, "likes": 18, "updated": 1744244093, "created": 1744244093, "version": "1.0", "sizeBytes": 231737, "tags": ["Skins"], "url": "https://gamebanana.com/mods/587443", "installable": true, "file": "enadeck.zip", "md5": "c8d4459685228540db3ba675f7d0d191"},
  {"ref": "gb:Mod:597157", "source": "gb", "game": "balatro", "title": "Isopixl's Indie Deck", "summary": "A card retexture mod of some of my favourite games! Replaces Ace, King, Queen and Jack Games: - Hyper Light Drifter - OneShot - Hollow Knight - Celeste", "author": "Isopixl", "icon": "https://images.gamebanana.com/img/ss/mods/530-90_683aa1eeca039.jpg", "downloads": 1202, "likes": 10, "updated": 1752327878, "created": 1748446726, "version": "1.2", "sizeBytes": 203918, "tags": ["Skins"], "url": "https://gamebanana.com/mods/597157", "installable": true, "file": "isopixl_s_indie_deck_fixed.zip", "md5": "7b6cff985f726ff0854d19615ffb2fc4"},
  {"ref": "gb:Mod:578129", "source": "gb", "game": "balatro", "title": "May and Bridget from Guilty Gear as Face Cards", "summary": "Replaces the default face cards king, queen, and jack, to May, Bridget, and Roger, from Guilty Gear Strive respectively. Steammodded needs to be installed for this to work. Thank you to @mayaisanimating for some of the design ideas! For any", "author": "mashowo", "icon": "https://images.gamebanana.com/img/ss/mods/530-90_67c089f332666.jpg", "downloads": 994, "likes": 20, "updated": 1740722339, "created": 1740671848, "sizeBytes": 172281, "tags": ["Skins"], "url": "https://gamebanana.com/mods/578129", "installable": true, "file": "mayburideck.zip", "md5": "84f892064a8eb0431931d3faa734be9d"},
  {"ref": "mr:P7dR8mSH", "source": "mr", "game": "minecraft", "title": "Fabric API", "summary": "Lightweight and modular API providing common hooks and intercompatibility measures utilized by mods using the Fabric toolchain.", "author": "modmuss50", "icon": "https://cdn.modrinth.com/data/P7dR8mSH/icon.png", "downloads": 270782295, "likes": 36674, "updated": 1791301794, "created": 1611313481, "tags": ["library"], "url": "https://modrinth.com/mod/fabric-api", "installable": true},
  {"ref": "mr:AANobbMI", "source": "mr", "game": "minecraft", "title": "Sodium", "summary": "A high-performance rendering engine replacement for Minecraft, which greatly improves frame rates and reduces micro-stutter.", "author": "jellysquid3", "icon": "https://cdn.modrinth.com/data/AANobbMI/295862f4724dc3f78df3447ad6072b2dcd3ef0c9_96.webp", "downloads": 238896364, "likes": 41530, "updated": 1789939626, "created": 1609635214, "tags": ["optimization"], "url": "https://modrinth.com/mod/sodium", "installable": true},
  {"ref": "mr:YL57xq9U", "source": "mr", "game": "minecraft", "title": "Iris Shaders", "summary": "A modern shader pack loader for Minecraft intended to be compatible with existing OptiFine shader packs", "author": "coderbot", "icon": "https://cdn.modrinth.com/data/YL57xq9U/18d0e7f076d3d6ed5bedd472b853909aac5da202_96.webp", "downloads": 185788796, "likes": 29795, "updated": 1790737098, "created": 1622092275, "tags": ["decoration", "optimization"], "url": "https://modrinth.com/mod/iris", "installable": true},
  {"ref": "mr:NNAgCjsB", "source": "mr", "game": "minecraft", "title": "Entity Culling", "summary": "Using async path-tracing to hide Block-/Entities that are not visible", "author": "tr7zw", "icon": "https://cdn.modrinth.com/data/NNAgCjsB/7873452d6cede4daed12da3d7d8c193ab88b4fd6_96.webp", "downloads": 177125832, "likes": 17701, "updated": 1791478340, "created": 1653473349, "tags": ["optimization"], "url": "https://modrinth.com/mod/entityculling", "installable": true},
  {"ref": "mr:9s6osm5g", "source": "mr", "game": "minecraft", "title": "Cloth Config API", "summary": "Configuration Library for Minecraft Mods", "author": "shedaniel", "icon": "https://cdn.modrinth.com/data/9s6osm5g/ed8a2316cbb6f4fc5f510e8e13a59a85cbbbff4d_96.webp", "downloads": 175549671, "likes": 16818, "updated": 1790146850, "created": 1650536981, "tags": ["library"], "url": "https://modrinth.com/mod/cloth-config", "installable": true},
  {"ref": "mr:uXXizFIs", "source": "mr", "game": "minecraft", "title": "FerriteCore", "summary": "Memory usage optimizations", "author": "malte0811", "icon": "https://cdn.modrinth.com/data/uXXizFIs/222a126f26f8f9ae1eb339f3b767677f18bff31f_96.webp", "downloads": 157184598, "likes": 16506, "updated": 1774377108, "created": 1617433483, "tags": ["optimization", "utility"], "url": "https://modrinth.com/mod/ferrite-core", "installable": true},
  {"ref": "mr:mOgUt4GM", "source": "mr", "game": "minecraft", "title": "Mod Menu", "summary": "Adds a mod menu to view the list of mods you have installed.", "author": "Prospector", "icon": "https://cdn.modrinth.com/data/mOgUt4GM/5a20ed1450a0e1e79a1fe04e61bb4e5878bf1d20.png", "downloads": 151376707, "likes": 27467, "updated": 1790282641, "created": 1604639464, "tags": ["utility"], "url": "https://modrinth.com/mod/modmenu", "installable": true},
  {"ref": "mr:gvQqBUqZ", "source": "mr", "game": "minecraft", "title": "Lithium", "summary": "No-compromises game logic optimization mod, useful for both single-player games and multi-player servers.", "author": "jellysquid3", "icon": "https://cdn.modrinth.com/data/gvQqBUqZ/bcc8686c13af0143adf4285d741256af824f70b7_96.webp", "downloads": 133536191, "likes": 23788, "updated": 1790567011, "created": 1609635412, "tags": ["optimization"], "url": "https://modrinth.com/mod/lithium", "installable": true},
];

const GAMES: ModGame[] = [
  // r2modman layout (Thunderstore ecosystem schema): the BepInEx pack into the game folder, plugins into their own folder.
  {
    game: 'lethal', name: 'Lethal Company', steam: '1966720',
    sources: { ts: { community: 'lethal-company' }, nx: { domain: 'lethalcompany' }, cf: { gameId: 83671 }, gb: { gameId: 19344 } },
    targets: [
      { source: 'ts', match: 'BepInEx-BepInExPack', dst: '{game}', root: 'BepInExPack', unpack: true },
      { source: 'ts', dst: '{game}/BepInEx/plugins/{ns}-{name}', unpack: true },
      { dst: '{game}/BepInEx/plugins', unpack: true },
    ],
  },
  { game: 'balatro', name: 'Balatro', steam: '2379780', sources: { nx: { domain: 'balatro' }, gb: { gameId: 21356 } }, targets: [{ dst: '{game}/Mods', unpack: true }] },
  { game: 'skyrim', name: 'The Elder Scrolls V: Skyrim Special Edition', steam: '489830', sources: { nx: { domain: 'skyrimspecialedition' }, mio: { gameId: 0 } }, targets: [{ dst: '{game}/Data', unpack: true }] },
  { game: 'minecraft', name: 'Minecraft: Java Edition', sources: { mr: {}, cf: { gameId: 432, classId: 6 } }, targets: [{ dst: '{game}/mods', unpack: false }] },
];

/** Tools, not mods: the app sends players to their page. */
const LINK_ONLY: Record<string, string> = { 'nx:skyrimspecialedition:6194': 'no_target', 'nx:skyrimspecialedition:3038': 'no_target' };

const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));
const flagValue = (k: string) => (typeof location === 'undefined' ? null : new URLSearchParams(location.search).get(k));
const keep = (key: string, v: unknown) => {
  try {
    localStorage.setItem(key, JSON.stringify(v));
  } catch {}
};
const stored = <T,>(key: string): T | null => {
  try {
    return JSON.parse(localStorage.getItem(key) ?? '') as T;
  } catch {
    return null;
  }
};

const INSTALLED = 'mods-sim-installed';
const card = (s: Sample): ModItem => {
  const { deps: _d, file: _f, md5: _m, ...it } = s;
  const why = LINK_ONLY[s.ref];
  return why ? { ...it, installable: false, why } : it;
};
const byRef = (ref: string) => SAMPLE.find((s) => s.ref === ref);

function filesOf(s: Sample): ModFile[] {
  if (s.source === 'nx') {
    const id = Number(s.ref.split(':')[2]);
    return [
      { id: String(id * 37 + 1009), name: s.title, version: s.version, sizeBytes: s.sizeBytes, updated: s.updated, primary: true, category: 'main' },
      ...(s.version && s.updated && s.created && s.updated - s.created > 86400 * 30 ? [{ id: String(id * 37 + 11), name: s.title, version: '1.0.0', sizeBytes: s.sizeBytes ? Math.round(s.sizeBytes * 0.8) : undefined, updated: s.created, category: 'old_version' }] : []),
    ];
  }
  return [{ id: s.version ?? '1', name: s.file ?? s.title, version: s.version, sizeBytes: s.sizeBytes, updated: s.updated, primary: true }];
}

function planFile(s: Sample, of: string): PlanFile {
  const [, ns] = /^ts:([^-]+)-/.exec(s.ref) ?? [];
  switch (s.source) {
    case 'ts': {
      const full = s.ref.slice(3);
      const pack = full === 'BepInEx-BepInExPack';
      return { url: `https://gcdn.thunderstore.io/live/repository/packages/${full}-${s.version}.zip`, size: s.sizeBytes, name: `${full}-${s.version}.zip`, unpack: true, dst: pack ? '{game}' : `{game}/BepInEx/plugins/${ns}-${full.slice(ns.length + 1)}`, root: pack ? 'BepInExPack' : undefined, of };
    }
    case 'gb':
      return { url: `https://files.gamebanana.com/mods/${s.file ?? 'mod.zip'}`, size: s.sizeBytes, hash: s.md5 ? { md5: s.md5 } : undefined, name: s.file ?? 'mod.zip', unpack: true, dst: s.game === 'balatro' ? '{game}/Mods' : '{game}/BepInEx/plugins', of };
    case 'mr':
      return { url: `https://cdn.modrinth.com/data/${s.ref.slice(3)}/versions/latest/${s.title.toLowerCase().replace(/\W+/g, '-')}.jar`, size: s.sizeBytes, name: `${s.title}.jar`, unpack: false, dst: '{game}/mods', of };
    default:
      return { url: '', size: s.sizeBytes, name: `${s.title}-${s.version ?? '1'}.zip`, unpack: true, dst: s.game === 'skyrim' ? '{game}/Data' : s.game === 'balatro' ? '{game}/Mods' : '{game}/BepInEx/plugins', of };
  }
}

/** Thunderstore dependencies, deepest first, each once. */
function depsOf(s: Sample, seen = new Set<string>()): Sample[] {
  const out: Sample[] = [];
  for (const name of s.deps ?? []) {
    const d = byRef(`ts:${name}`);
    if (!d || seen.has(d.ref)) continue;
    seen.add(d.ref);
    out.push(...depsOf(d, seen), d);
  }
  return out;
}

/** The simulated backend; `onProgress` gets the events the core would send on `install://progress`. */
export function simModsBackend(onProgress: (p: { id: string; phase: 'download' | 'verify' | 'install' | 'ready'; pct: number }) => void): ModsBackend {
  const nxFlag = flagValue('nx');
  let nexus: NexusStatus = nxFlag === 'out' || nxFlag === 'soon' ? { loggedIn: false } : { loggedIn: true, name: 'quietfox', premium: nxFlag === 'premium' };
  const now = Math.floor(Date.now() / 1000);
  // Vortex answered nxm:// links before SIGF on this sample PC.
  let nxm = { supported: true, enabled: false, other: true };
  const installed = (): InstalledModRow[] =>
    stored<InstalledModRow[]>(INSTALLED) ?? [
      { ref: 'ts:BepInEx-BepInExPack', game: 'lethal', name: 'BepInExPack', version: '5.4.2305', at: now - 9 * 86400 },
      { ref: 'ts:notnotnotswipez-MoreCompany', game: 'lethal', name: 'MoreCompany', version: '1.12.0', at: now - 9 * 86400 },
      { ref: 'ts:x753-More_Suits', game: 'lethal', name: 'More Suits', version: '1.6.2', at: now - 4 * 86400 },
      { ref: 'nx:skyrimspecialedition:12604', game: 'skyrim', name: 'SkyUI', version: '5.2SE', at: now - 30 * 86400 },
    ];
  const sorts = {
    popular: (a: ModItem, b: ModItem) => (b.downloads ?? 0) - (a.downloads ?? 0),
    updated: (a: ModItem, b: ModItem) => (b.updated ?? 0) - (a.updated ?? 0),
    new: (a: ModItem, b: ModItem) => (b.created ?? 0) - (a.created ?? 0),
  };
  return {
    games: async () => {
      await wait(200);
      return GAMES;
    },
    search: async (game, source, o) => {
      await wait(450 + Math.random() * 500);
      if (source === 'cf' || source === 'mio') throw new ModsError('source_unavailable', 'source_unavailable');
      const q = o.q?.trim().toLowerCase();
      const list = SAMPLE.filter((s) => s.game === game && s.source === source && (!q || `${s.title} ${s.summary} ${s.author} ${s.tags.join(' ')}`.toLowerCase().includes(q))).map(card).sort(sorts[o.sort]);
      const at = Number(o.cursor ?? 0);
      const size = 10;
      return { items: list.slice(at, at + size), next: at + size < list.length ? String(at + size) : null, total: list.length };
    },
    item: async (ref) => {
      await wait(300);
      const s = byRef(ref);
      if (!s) throw new ModsError('not_found', ref);
      return { ...card(s), description: s.summary, files: filesOf(s) };
    },
    plan: async (ref, game) => {
      await wait(500);
      const s = byRef(ref);
      if (!s) throw new ModsError('not_found', ref);
      const base = { ref, game, name: s.title, version: s.version ?? '1.0.0' };
      if (LINK_ONLY[ref]) return { ...base, files: [], deps: [], link: { url: s.url, why: LINK_ONLY[ref] } };
      if (s.source === 'nx') {
        const [, domain, modId] = ref.split(':');
        const files = filesOf(s);
        return { ...base, files: [planFile(s, ref)], deps: [], needs: 'nxm', nx: { domain, modId, fileId: files[0]?.id ?? null, filesUrl: `${s.url}?tab=files`, files } };
      }
      // Minecraft mods go through the Minecraft flow (a Prism instance), not a game folder.
      if (s.source === 'mr') return { ...base, files: [], deps: [], link: { url: s.url, why: 'use_minecraft_flow' } };
      const deps = depsOf(s);
      return { ...base, files: [...deps.map((d) => planFile(d, d.ref)), planFile(s, ref)], deps: deps.map((d) => ({ ref: d.ref, name: d.title, version: d.version ?? '' })) };
    },
    install: async (plan: InstallPlan) => {
      const id = `mod/${plan.ref}`;
      const steps: ['download' | 'verify' | 'install', number, number][] = [['download', 0, 70], ['verify', 70, 80], ['install', 80, 100]];
      for (const [phase, from, to] of steps) {
        const n = phase === 'download' ? 12 : 4;
        for (let k = 1; k <= n; k++) {
          await wait(phase === 'download' ? 180 + Math.random() * 140 : 160);
          onProgress({ id, phase, pct: from + ((to - from) * k) / n });
        }
      }
      const rows = installed().filter((r) => r.ref !== plan.ref);
      keep(INSTALLED, [...rows, { ref: plan.ref, game: plan.game, name: plan.name, version: plan.version, at: Math.floor(Date.now() / 1000) }]);
      onProgress({ id, phase: 'ready', pct: 100 });
    },
    uninstall: async (ref) => {
      await wait(700);
      keep(INSTALLED, installed().filter((r) => r.ref !== ref));
    },
    installed: async () => {
      await wait(150);
      return installed();
    },
    nexusStatus: async () => {
      await wait(250);
      if (nxFlag === 'soon') throw new ModsError('nexus_unavailable', 'nexus_unavailable');
      return nexus;
    },
    nexusLogin: async () => {
      await wait(1200);
      if (nxFlag === 'soon') throw new ModsError('nexus_unavailable', 'nexus_unavailable');
      nexus = { loggedIn: true, name: 'quietfox', premium: false };
      return nexus;
    },
    nexusLogout: async () => {
      await wait(300);
      nexus = { loggedIn: false };
    },
    nexusSetKey: async (key) => {
      await wait(900);
      if (!/^[A-Za-z0-9+/=_-]{16,512}$/.test(key.trim()) || /bad/i.test(key)) throw new ModsError('needs_nexus_login', 'nexus_key_invalid');
      nexus = { loggedIn: true, name: 'quietfox', premium: /premium/i.test(key) };
      return nexus;
    },
    nexusLink: async (domain, modId, fileId) => {
      await wait(400);
      return `https://supporter-files.nexus-cdn.com/${domain}/${modId}/${fileId}.zip`;
    },
    nxmHandler: async (enable) => {
      await wait(200);
      nxm = { ...nxm, enabled: enable, other: enable ? false : nxm.other };
      return enable;
    },
    nxmState: async () => {
      await wait(150);
      return nxm;
    },
  };
}
